#!/usr/bin/env bash

PACKAGE_NAME="mausy5043-common"

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)
CMD="${1}"
BRANCH="$(git branch --show-current)"
echo "$HERE is on branch: $BRANCH"
echo

pushd "${HERE}" >/dev/null || exit 1

build_app(){
    LOCATION=$1
    echo "Building distribution package in $LOCATION"
    ### install build-system
    echo
    echo "Checking build-system installation..."
    python -m pip install --upgrade build | grep -v "already satisfied"
    python -m pip install --upgrade twine | grep -v "already satisfied"
    ### build package
    echo
    make_go
    echo "Building app..."
    rm -r dist/* 2>/dev/null || true
    rm -r ./*.egg-info 2>/dev/null || true
    python -m build --outdir ./dist # not needed by default: --sdist --wheel
}

test_app() {
    LOCATION=$1
    echo "Upload package to TestPyPi from $LOCATION"
    python -m twine upload --repository testpypi dist/*
    echo ""
    echo "To test installing this package use:"
    echo "python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ --no-deps --upgrade ${PACKAGE_NAME}"
}

dist_app() {
    LOCATION=$1
    echo "Upload distribution package to PyPi from $LOCATION"
    python -m twine upload --repository pypi dist/*
    echo ""
    echo "To install this package use:"
    echo "python -m pip install --upgrade ${PACKAGE_NAME}"
}

update_local_repo() {
    branch_name=$1
    git fetch origin "${branch_name}" || { sleep 60; git fetch origin "${branch_name}" || exit 1; }
    git reset --hard "origin/${branch_name}" || exit 1
    git clean -f -d || exit 1
    git pull || exit 1
}

make_go() {
    echo "Building Go binaries..."
    pushd src/mausy5043_common/_fastmeteo >/dev/null || exit 1
        # go mod init fastmeteo
        rm bin/* 2>/dev/null || true
        go mod tidy
        # mkdir -p bin
        # go build -o bin/meteo
        GOOS=linux GOARCH=arm64 go build -o bin/meteo-linux-arm64
        GOOS=linux GOARCH=amd64 go build -o bin/meteo-linux-amd64
        GOOS=darwin GOARCH=arm64 go build -o bin/meteo-darwin-arm64
        GOOS=darwin GOARCH=amd64 go build -o bin/meteo-darwin-amd64
        GOOS=windows GOARCH=arm64 go build -o bin/meteo-windows-arm64.exe
        GOOS=windows GOARCH=amd64 go build -o bin/meteo-windows-amd64.exe
    popd >/dev/null || exit 1
}

# check commandline parameters
case $CMD in
    -b | --build)
        # build
        build_app "${HERE}" || exit 1
        ;;
    -d | --dist)
        # distribute for production
        dist_app "${HERE}" || exit 1
        ;;
    -t | --test)
        # distribute for testing
        test_app "${HERE}" || exit 1
        ;;
    --discard)
        # reset local repo discarding local changes
        update_local_repo "${BRANCH}" || exit 1
        ;;
    -g | --go)
        # build golang binaries
        make_go
        ;;
    *)
        echo "Syntax:"
        echo "mkbld [-b|--build] | [-d|--dist] | [-t|--test] | [--discard]"
        echo "Only the first option past is executed!"
        echo
        exit 1
        ;;
esac

popd >/dev/null || exit 1
